#!/bin/bash


cd /Users/andreamitridate/code/nanograv/15yr/non-bhb

MODEL="string_meta_l"
NUMERICS="full_run"
PTA="nanograv_15"

DMPS=/Users/andreamitridate/code/nanograv/15yr/non-bhb/sampler.py

# run script
python $DMPS \
    -m "${MODEL}.py" \
    -n "${NUMERICS}.py" \
    -p "${PTA}.py" \
    -c 0 \
/

