from enterprise.signals.parameter import function
import enterprise.signals.parameter as parameter
import scipy.constants as scon
#import numpy as np
#import src.models_utils as aux

name = 'pbh_static' # name of the model
mod_sel = True # set to True if you want to compare the model to the SMBHB signal
smbhb = True # set to True if you want to overlay the new-physics signal to the SMBHB signal
corr = False # set to True if you want to include spatial correlations in the analysis 
parameters ={
    "log10_A_stat_dm" : parameter.Uniform(-21, -13)('log10_A_stat_dm'),
}
group = ['log10_A_stat_dm']
@function
def signal(toas, log10_A_stat_dm):
    """
    Function that calculates the static pulsar term signal generated by
    DM substructure
    :param toas: Time-of-arrival measurements [s]
    :param log10_A: log10 of GW strain
    :param log10_f: log10 of GW frequency
    :param phase_p: The Pulsar-term phase of the GW
    :return: the waveform as induced timing residuals (seconds)
    """
    
    # convert 
    A = 10 ** log10_A_stat_dm
    
    # return timing residual in seconds
    return A * (toas**3) / (scon.Julian_year**2)
