from enterprise.signals.parameter import function
import enterprise.signals.parameter as parameter
import scipy.constants as scon
import numpy as np
import src.models_utils as aux

name = 'uldm_c_unc' # name of the model

smbhb = True # set to True if you want to overlay the new-physics signal to the SMBHB signal

parameters ={
    "log10_A_dm" : parameter.Uniform(-9, -4)('log10_A_dm'),
    "log10_f_dm" : parameter.Uniform(-10, -5.5)('log10_f_dm'),
    "gamma_p" : parameter.Uniform(0, 2 * np.pi),
    "gamma_e" : parameter.Uniform(0, 2 * np.pi)('gamma_e'),
    "phi_hat_sq_p" : aux.Gamma(1,0,1),
    "phi_hat_sq_e" : aux.Gamma(1,0,1)('phi_hat_sq_e')
}

group = ['log10_A_dm', 'log10_f_dm']

def pulsar_signal(toas, log10_A_dm, log10_f_dm, gamma_p, phi_hat_sq_p):
    
    A = 10**log10_A_dm
    f = 10**log10_f_dm

    # return timing residual in seconds
    return A * np.sqrt(phi_hat_sq_p) * np.sin(2 * np.pi * f * toas + gamma_p)

def earth_signal(toas, log10_A_dm, log10_f_dm, gamma_e, phi_hat_sq_e):
    
    A = 10**log10_A_dm
    f = 10**log10_f_dm

    # return timing residual in seconds
    return A * np.sqrt(phi_hat_sq_e) * np.sin(2 * np.pi * f * toas + gamma_e)

@function
def signal(toas, log10_A_dm, log10_f_dm, gamma_p, gamma_e, phi_hat_sq_p, phi_hat_sq_e):
    """
    Function that calculates the pulsar + earth signal generated by
    ultralight dark matter in the uncorrelated limit 
    :param toas: Time-of-arrival measurements [s]
    :param log10_A_dm: log10 of signal amplitude
    :param log10_f_dm: log10 of signal frequency
    :param phase_p: Pulsar-term phase
    :param phase_p: Earth-term phase
    :param phi_hat_sq_p: dm density fluctuation at the pulsar position
    :param phi_hat_sq_e: dm density fluctuation at the Earth position
    :return: the waveform as induced timing residuals (seconds)
    """

    p_s = pulsar_signal(toas, log10_A_dm, log10_f_dm, gamma_p, phi_hat_sq_p)
    e_s = earth_signal(toas, log10_A_dm, log10_f_dm, gamma_e, phi_hat_sq_e)

    # return timing residual in seconds
    return p_s + e_s
    